version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - memory_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  # This is a supplementary service for the main SimuVerse Backend
  # It's not intended to be used standalone
  memory_service:
    build:
      context: .
      dockerfile: memory_system/Dockerfile
    ports:
      - "3001:3000"  # Different port to avoid conflict with main backend
    environment:
      - QDRANT_URL=http://qdrant
      - QDRANT_PORT=6333
      - PYTHONPATH=/app
    volumes:
      - ./memory_system:/app/memory_system
    depends_on:
      - qdrant
    networks:
      - memory_network
    restart: unless-stopped

networks:
  memory_network:
    driver: bridge

volumes:
  qdrant_data:
    driver: local