version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: simuverse-qdrant
    volumes:
      - qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"
      - "6334:6334"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/readiness"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  memory_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simuverse-memory
    depends_on:
      - qdrant
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - HOST=0.0.0.0
      - PORT=8000
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  qdrant_data:
    driver: local